### ISSUE TITLE
Time widget has weird 24-hours format

### ISSUE THREAD

**Issue by Nickfrm** [rigami/readme#13]
It shows 24 instead of 00:

![image](https://user-images.githubusercontent.com/35500726/122833575-e1ad8d00-d2f5-11eb-8bdd-8079bd4479a1.png)

**Comment by danilkinkin** [comment]
Hello, sorry for late answer. Now i'm migrate to new extensions API (MV3).

I checked if there really is such a problem. Fixed in next release
