### ISSUE TITLE
Implement ability to toggle cards view to list view

### ISSUE THREAD

**Issue by Nickfrm** [rigami/readme#14]
Implement the ability to toggle cards view to list view, e.g.:

![image](https://user-images.githubusercontent.com/35500726/123156436-f3b43a80-d471-11eb-9bc6-f756086ee36c.png)

It can contain the full URL instead of hostname only in this view.

**Comment by danilkinkin** [comment]
Hello, sorry for late answer. Now i'm migrate to new extensions API (MV3).

Thank you, this is interesting, I'll think about it

**Comment by danilkinkin** [comment]
Will be done in rigami 2.0 milestone https://github.com/orgs/rigami/projects/5/views/1
