### ISSUE TITLE
Одинаковые иконки

### ISSUE THREAD

**Issue by zlocorp** [rigami/readme#4]
Мне кажется что 2 одинаковые иконки выполняющие разные функции немного не то :)

![image](https://user-images.githubusercontent.com/5073610/108732739-77c1da00-74f3-11eb-9d9c-acc901865a8b.png)

**Comment by danilkinkin** [comment]
Вы правы, это действительно не очень хорошо. Не обратил внимание на это при разработке.

Поправлю иконку в следующей версии, спасибо.

**Comment by danilkinkin** [comment]
Исправлено в версии v0.3.8
