### ISSUE TITLE
Взаимодействие с CCleaner

### ISSUE THREAD

**Issue by MisterUnrea** [rigami/readme#5]
Заметил, что с ClockTab перекочевала проблема взаимодействия с клинером: теряются все фоны и иконки сайтов. Есть ли способы как-то защитить данные от чистки? 
Очень неудобно каждый раз удалять и ставить расширение и настраивать с нуля.
Мои мысли пока привели к двум вероятным способам решения:
Сохранять данные об изображениях в настроечном файле.
Добавить функцию перезагрузки в приложение - просто аналог хард-ресета, избавляющий пользователя от забега по магазину расширений Хрома.

**Comment by danilkinkin** [comment]
Здраствуйте, похоже что CCleaner очищает вообще все данные в браузере. Не уверен, что возможно как то защитить данные от этого.

А вообще очень странно то, что удалаются фоны, но не стираются настройки.

Попробую добавить фоны и иконки в файл бекапа, тогда после чистки можно будет востановить данные. Я уже пытался это сделать, но тогда не нашел решения. Основные сложности были со сборкой файла бекапа, объеденением настроек и фонов в один файл. Сейчас покапался и нашел несколько вариантов, протестирую их и отпушусь

**Comment by danilkinkin** [comment]
Добавил возможность сохранения фонов в бекап. Не уверен что это хорошая идея, так как файлы бекапа могут в таком случае могут выростать до гигабайта. Посмотрю в будующем как можно это улучшить.

Не рекомендую использовать этот функционал,  только в крайнем случае, если нужно полностью перенести данные.

Выглядит вот так:
![image](https://user-images.githubusercontent.com/10831688/112735800-7eff5c00-8f67-11eb-8abf-81d0b7266211.png)

Появится этот функционал  в следующем обновлении
