### ISSUE TITLE
Фоны не загружаются

### ISSUE THREAD

**Issue by zlocorp** [rigami/readme#6]
Добрый день. 
Проблема с фонами. Постоянно (95%) вот такая надпись ИЗ кеша не грузит, потому как их загруженных вместо 5 - один.
Какие логи нужны?

![image](https://user-images.githubusercontent.com/5073610/114298760-8cdfd180-9a7d-11eb-88e8-6f712c48c0fb.png)

![image](https://user-images.githubusercontent.com/5073610/114298795-ac76fa00-9a7d-11eb-94e1-ac382531005d.png)

**Comment by danilkinkin** [comment]
Обновил rigami (версия 0.11.0), поправил  много пробелем с фонами, скажите пробелма еще наблюдается?

**Comment by zlocorp** [comment]
К сожалению да. Уже словил бесконечную загрузку фона.

Потом уже сменил поток на - "темные" и вот что заметил. Я вручную нажимаю кнопку обновить, фон прекрасно подгружается, но НЕ кэшируется (в списке одна картинка которая там была). Может стоит добавить еще и кеширование при ручном обновлении?

**Comment by danilkinkin** [comment]
Сейчас кэшируется при любом обновлении на 4 фона впрёд. А перезагрузка расширения не помогает?

Могли бы вы сказать примерные шаги для воспроизведения проблемы? Попробую отловить ошибку и поправить.


Спасибо за ваше сообщение, постараюсь исправить эту проблему

**Comment by zlocorp** [comment]
![image](https://user-images.githubusercontent.com/5073610/115266275-bfa25d80-a140-11eb-8350-61008591f817.png)
Вот так показывает в настройках. Кешированных нет, хотя несколько раз нажал на кнопку ручного обновления и картинки обновились.
Поставил на 5 минут, картинки тоже менялись (уже хорошо), но не кешировались.
Сейчас вернул на 1 час. Посмотрю что будет.

**Comment by danilkinkin** [comment]
Наверно возникло недопонимание, кешированные фоны не отображаются в библиотеке. В библиотеке отображаются только сохранённые фоны. Самый простой способ проверить кэширование, подождать какое-то время (минуты 2) и попробовать вручную поменять фон несколько раз (нажимать на кнопку "Следующий фон"), если фоны меняются без загрузки, то фоны кэшируются, как только начнется долгая загрузка, значит кэш кончился и они снова подгружаются.

**Comment by zlocorp** [comment]
Тогда может стоит добавить туда вывод кэшированных?

Буду смотреть дальше по глюкам с обложками

**Comment by danilkinkin** [comment]
Не уверен, что стоит показывать, где-то список кэшированных фонов, это больше внутренняя информация и большинство пользователей она будет путать, будут недопонимания почему фоны есть, а потом они пропали из их библиотеки.

Есть мысли заменить кнопку сохранения фона на кнопку 'лайка', если фон понравился, то лайкнул его и он автоматически добавился в библиотеку, это поведение прозрачно и понятно, и такой кнопкой будут пользоваться чаще чем копкой сохранения фона.

**Comment by zlocorp** [comment]
Можно сделать рядом с библиотекой "последние просмотренные". Там и будут закешированные фоны лежать. Но это на ваше усмотрение. 
Кнопку лайка да, можно сделать, понравился фон, добавил в библиотеку.

Касательно проблемы, пока непонятно, фоны обновляются, проблем явных не вижу. Буду наблюдать

**Comment by danilkinkin** [comment]
Но кэш это же не назад, а вперед (следующие фоны).

Насчет кнопки 'лайка', добавил в [беклог](https://github.com/orgs/rigami/projects/1#card-59747713), как будет время сделаю.

Хорошо, отлично что пока нет проблем, если возникнут пишите
