### ISSUE TITLE
Cannot create a bookmark "yandex maps"

### ISSUE THREAD

**Issue by Nickfrm** [rigami/readme#7]
Cannot create a bookmark "yandex maps" or "яндекс карты". This error can probably be applied to some other websites. I've attached .gif how to reproduce it and the screenshot with the error.

![rigami_error](https://user-images.githubusercontent.com/35500726/122756311-edba3000-d29e-11eb-98d7-5f1e3d7122f8.gif)

![image](https://user-images.githubusercontent.com/35500726/122756405-0aeefe80-d29f-11eb-9322-88c41070b35a.png)

**Comment by danilkinkin** [comment]
Hello, sorry for late answer. Now i'm migrate to new extensions API (MV3).

So far, I have not been able to replicate this problem. Tell me if it can be observed with other addresses?

**Comment by Nickfrm** [comment]
This issue appears for me when the URL contains such text:
- "andex.ru/map"
- "yandex.ru/map"
- "andex.ru"
- and etc

Let me know if you need any other info about that

**Comment by danilkinkin** [comment]
Thanks, I will try to experiment with these urls soon

**Comment by danilkinkin** [comment]
Fixed in next release
